In [1]:
## import numpy as np

In [2]:
import numpy as np

In [3]:
## create an array of 10 zeros

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
## create an array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
## create an array of 10 fives
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [16]:
## create an array of 10,50
np.arange(10,50,dtype='float')

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
       36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48.,
       49.])

In [19]:
## create an array 3x3 values ranging from 0 to 8
x=np.arange(0,9)
print(x.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [20]:
## create an identity matrix 3x3
x=np.eye(3,3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
## generate an random number from 0 to 1
x=np.random.randn(0,1)
print(x)

[]


In [25]:
x

array([], shape=(0, 1), dtype=float64)

In [36]:
## create an array like this
x=np.arange(1,101)/100
x.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [38]:
x=np.linspace(0.01,1,100)/100
print(x.reshape(10,10))

[[0.0001 0.0002 0.0003 0.0004 0.0005 0.0006 0.0007 0.0008 0.0009 0.001 ]
 [0.0011 0.0012 0.0013 0.0014 0.0015 0.0016 0.0017 0.0018 0.0019 0.002 ]
 [0.0021 0.0022 0.0023 0.0024 0.0025 0.0026 0.0027 0.0028 0.0029 0.003 ]
 [0.0031 0.0032 0.0033 0.0034 0.0035 0.0036 0.0037 0.0038 0.0039 0.004 ]
 [0.0041 0.0042 0.0043 0.0044 0.0045 0.0046 0.0047 0.0048 0.0049 0.005 ]
 [0.0051 0.0052 0.0053 0.0054 0.0055 0.0056 0.0057 0.0058 0.0059 0.006 ]
 [0.0061 0.0062 0.0063 0.0064 0.0065 0.0066 0.0067 0.0068 0.0069 0.007 ]
 [0.0071 0.0072 0.0073 0.0074 0.0075 0.0076 0.0077 0.0078 0.0079 0.008 ]
 [0.0081 0.0082 0.0083 0.0084 0.0085 0.0086 0.0087 0.0088 0.0089 0.009 ]
 [0.0091 0.0092 0.0093 0.0094 0.0095 0.0096 0.0097 0.0098 0.0099 0.01  ]]


In [39]:
## numpy indexing and selecting

In [105]:
x=np.arange(1,26).reshape(5,5)
print(x)
print(x[:3,:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [104]:
x=np.arange(1,26).reshape(5,5)
print(x)
print(x[:3,2:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [107]:
x=np.arange(1,26).reshape(5,5)
print(x[2:,:3])

[[11 12 13]
 [16 17 18]
 [21 22 23]]


In [109]:
x=np.arange(1,26).reshape(5,5)
print(x[2:,2:])

[[13 14 15]
 [18 19 20]
 [23 24 25]]


In [113]:
x=np.arange(1,26).reshape(5,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [114]:
x=np.arange(1,26).reshape(5,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [122]:
x[:,2]+2

array([ 5, 10, 15, 20, 25])

In [123]:
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [135]:
x=np.arange(1,26).reshape(5,5)
print(x[3:],end='\n')
print(x[-2:])

[[16 17 18 19 20]
 [21 22 23 24 25]]
[[16 17 18 19 20]
 [21 22 23 24 25]]


In [136]:
x.sum()

325

In [138]:
print(x.std())

7.211102550927978
