# numpy array

In [2]:
import numpy as np
arr=[0,1,2]
np.array(arr)

array([0, 1, 2])

In [3]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)
np.size(my_mat)

9

In [7]:
np.array([1,2,3])

TypeError: array() got an unexpected keyword argument 'ndim'

In [8]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr=np.array([1,2.,3.])
print(arr)

[[[[[[1. 2. 3.]]]]]]


In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [21]:
## identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.random.rand(5,5)

array([[0.38453735, 0.20653457, 0.63646454, 0.13217257, 0.26591115],
       [0.78504684, 0.3857099 , 0.71271238, 0.14828135, 0.97025944],
       [0.71986136, 0.72980243, 0.04776224, 0.96552951, 0.31761778],
       [0.13576362, 0.07646418, 0.42245408, 0.26191901, 0.8361797 ],
       [0.1403678 , 0.95097171, 0.96442204, 0.77229008, 0.32205019]])

In [32]:
np.random.randn(4)

array([ 1.96058715, -0.97490612,  0.40344504, -0.61398479])

In [37]:
np.random.randint(1,100,10)

array([28, 10, 39, 12, 36, 82, 35, 88,  1, 20])

In [40]:
## matrix operation
arr=np.arange(25)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
arr2=np.arange(25)
arr.reshape(5,5)
print((arr+arr2).reshape(5,5))

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]


In [49]:
print(arr.max())
print(arr.min())
print((arr+arr2).max())
print((arr+arr2).min())
print(arr.shape)

24
0
48
0
(25,)


In [50]:
arr.dtype

dtype('int32')

In [52]:
from numpy.random import  randint
randint(2,3)

2