In [1]:
import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
x[0]

array([1, 2, 3])

In [3]:
x[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [4]:
x[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [5]:
x.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [6]:
x2=np.arange(0,9)
print(x2.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
### numpy selection and indexing

In [8]:
import numpy as np

In [9]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(arr_2d[0,0])

In [ ]:
print(arr_2d[0][1])

In [ ]:
print(arr_2d[:2,1:])

In [ ]:
print(arr_2d)

In [ ]:
print(arr_2d[1:,1:])

In [ ]:
print(arr_2d[0:2][:3])

In [ ]:
arr2=np.arange(1,11)

In [ ]:
print(arr2.size)

In [ ]:
arr2[arr2>5]

In [ ]:
arr2[arr2<5]

In [ ]:
bool_arr=arr2>5
print(bool_arr)

In [17]:
arr=np.arange(0,10)

In [18]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
(np.sqrt(arr)).reshape(2,5)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])